//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCode
    {
        public int CustomerCodeId { get; set; }
        public int CustomerId { get; set; }
        public string Code { get; set; }
        public string ContactNo { get; set; }
        public string ContactPerson { get; set; }
        public string EmailID { get; set; }
        public string UnitNo { get; set; }
        public string BuildingNo { get; set; }
        public string StreetName { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string RecordStatus { get; set; }
    }
}
